on:
  push:
    branches: [ main ]

permissions: #需要写入权限 否则不行 https://github.com/JamesIves/github-pages-deploy-action
  contents: write

jobs:
  pnpm-build:
    name: 构建admin前端
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: 更新 known_hosts 文件,否则无法进行后续连接  # 步驟的名稱
        run: |  # 將要執行的命令
          mkdir -p ~/.ssh 
          echo "----------------------"
          cat ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts
          echo "----------------------"
          cat ~/.ssh/known_hosts

      - name: Sign in to server #aa
        run: |
          ssh root@${{ secrets.HOST_NAME }}

      - name: Sign in to server #aa
        run: |
          ls
          echo "--------------"
          ls
          

#
#跑完之后会多一个 gp-pages分支，这个分支就是生产环境文件
#需要进行仓库settings--->page 指明使用gp pages分支

#原始配置中没有 actions/checkout@v4 步骤，
#这意味着工作流无法获取你的代码仓库内容