# 定义触发工作流的事件
on:
  push:  # 当有 push 操作时触发工作流
    branches: [ main ]  # 可选：指定触发分支（例如 main）
  # 也可以添加其他触发事件，例如：
  # pull_request:  # 当有 pull request 时触发
  # schedule:  # 定时触发
  #   - cron: '0 0 * * *'  # 每天午夜触发

# 定义工作流中的任务（jobs）
jobs:
  job1:  # 第一个任务
    runs-on: ubuntu-latest  # 在 Ubuntu 最新版环境中运行
    steps:
      - run: pwd  # 执行命令：打印当前工作目录
      - run: ls   # 执行命令：列出当前目录内容

  job2:  # 第二个任务
    runs-on: windows-latest  # 在 Windows 最新版环境中运行
    steps:
      - run: node --version  # 执行命令：打印 Node.js 版本
      - run: ls   # 执行命令：列出当前目录内容